### ISSUE TITLE
Get rid of TODO.md

### ISSUE THREAD

**Issue by madasi** [madasi/studious-octo-chainsaw#5]
Transform TODOs into Github Issues/feature requests

- [x] existing entries moved to Issues
- [ ] remove TOD.md

**Comment by madasi** [comment]
- [x] existing entries moved to Issues
- [ ] remove TOD.md

**Comment by madasi** [comment]
:metal:
